[package]
name = "rust-axum-intro"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Chone <jeremy.chone@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Rust Axum Full Course code."
homepage = "https://youtu.be/XZtlD_m59sM"
repository = "https://github.com/rust-httpc-test"

[dependencies]
tokio = { version = "1", features = ["full"] }
# Serde / json
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Axum
axum = "0.6.16"
tower-http = { version = "0.4.0", features = ["fs"] }


[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"




# * ğŸ’ Added that to make rust-analyzer work. Still don't know why I had issue with ssr...
[features]
ssr = []